# Gridworld 

In [1]:
import numpy as np

In [2]:
discount_factor = 1
actions = [[-1, 0], [1, 0], [0, 1], [0, -1]] #row +/- 1 or column +/- 1
max_iters = 1000
gridSize = 5

In [3]:
class Gridworld():
    def __init__(self, gridSize):
        self.valueMap = np.zeros((gridSize, gridSize))
        self.states = [[i, j] for i in range(gridSize) for j in range(gridSize)]
        self.size = gridSize
        self.new_pos = [0, 0] # initialize new position for p_transition
        self.pos_check = [0, 0] # a copy of new position
        
    def reward(self, current_pos, action):
        # normally, reward = 0
        reward = 0
        # if taking an action crosses the border = agent stays in same position
        if -1 in self.pos_check or self.size in self.pos_check: 
            reward = -1
        # if in state A, transition to state A'
        if current_pos == [0, 1]:
            reward = 10
        # if in state B, transition to state B'
        if current_pos == [0, 3]:
            reward = 5
        return reward
    
    def p_transition(self, current_pos, action):
        # get next position: state: [0, 0], action: [0, 1], new_state = [0, 1]
        self.new_pos = np.array(current_pos) + np.array(action)
        self.pos_check = self.new_pos # make a copy of new pos before being overwritten below
        # if taking an action crosses the border = agent stays in same position
        if -1 in self.new_pos or self.size in self.new_pos: 
            self.new_pos = current_pos
        # if in state A, transition to state A'
        if current_pos == [0, 1]:
            self.new_pos = [4, 1]
        # if in state B, transition to state B'
        if current_pos == [0, 3]:
            self.new_pos = [2, 3]
        return self.new_pos

## Policy Evaluation

In [4]:
grid = Gridworld(5)

In [5]:
# policy evaluation
for it in range(max_iters):
    valueMap_copy = np.copy(grid.valueMap)
    # start with the first state in the state list
    for state in grid.states:
        weightedRewards = 0
        # perform 4 actions per state and add the rewards (weightedRewards)
        for action in actions:
            # get next position and reward
            new_position = grid.p_transition(state, action)
            reward = grid.reward(state, action)
            # calculate weighted rewards: 1/4[r + gamma * value(s')]
            weightedRewards += (1/len(actions))*(reward+(discount_factor*grid.valueMap[new_position[0], new_position[1]]))
        # replace the value in valueMap with the weighted rewards
        valueMap_copy[state[0], state[1]] = round(weightedRewards,4)
    # overwrite the original value map
    grid.valueMap = valueMap_copy
    
    # print value map
    if it in [0,1,2,9, 99, 999, max_iters-1]:
        print("Iteration {}".format(it+1))
        print(grid.valueMap)
        print("")

Iteration 1
[[-0.5  10.   -0.25  5.   -0.5 ]
 [-0.25  0.    0.    0.   -0.25]
 [-0.25  0.    0.    0.   -0.25]
 [-0.25  0.    0.    0.   -0.25]
 [-0.5  -0.25 -0.25 -0.25 -0.5 ]]

Iteration 2
[[ 1.6875  9.75    3.4375  5.      0.4375]
 [-0.5     2.4375 -0.0625  1.1875 -0.5   ]
 [-0.4375 -0.0625  0.     -0.0625 -0.4375]
 [-0.5    -0.125  -0.0625 -0.125  -0.5   ]
 [-0.875  -0.5    -0.4375 -0.5    -0.875 ]]

Iteration 3
[[ 2.6562  9.5     4.2812  4.9375  0.8438]
 [ 0.5469  2.2812  1.7656  1.0938 -0.0781]
 [-0.625   0.4688 -0.0625  0.1562 -0.625 ]
 [-0.7344 -0.2812 -0.1719 -0.2812 -0.7344]
 [-1.1875 -0.7344 -0.625  -0.7344 -1.1875]]

Iteration 10
[[ 4.3514  8.351   5.3083  5.5598  2.0662]
 [ 2.4122  3.7326  3.0872  2.4848  0.9595]
 [ 0.4105  1.1042  1.0883  0.5556 -0.3513]
 [-1.1554 -0.5113 -0.457  -0.745  -1.4931]
 [-2.3268 -1.7418 -1.5663 -1.8444 -2.483 ]]

Iteration 100
[[ 3.3264  7.0172  4.4173  4.8326  1.703 ]
 [ 1.5906  2.8216  2.3572  1.8962  0.5286]
 [-0.4212  0.2766  0.2489 -0.1786

## Testing 

In [4]:
# get transition: starting in state [0, 0] with action [0, 1], the new state is [0, 1]
state = [0, 0]
action = [0, 1] # move right
grid = Gridworld(5)
new_position = grid.p_transition(state, action)
new_position

array([0, 1])